language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - flake8 --ignore=F401 twilio
  - flake8 --ignore=E123,E126,E128,E501 tests
  - nosetests
sudo: false
notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: TcDlBcKXtqmMdVsa3Lsofdqc1uVjqhZouwNETC260rByRb74gTHGZ1Da7PRkv+AZIFUq7S1uWTZXTXJTm154hi4aQb9SE2UowVwTJMjIKyy4P79s1eoyADP92cFEcpqSs4iVpU3t5srTj8cg2fVks8EsV5pDVJut1oBH4qYJEZw=
      - secure: qqtcwaS0y5e2SVm5g/zSRMgo7FcZ8Oa44bxQUDvJh/84/DHMD3zZoAv/A4+Vlbs0tCjnSKxMDuLxTzpiPgru4KPH7yj4fEXf7+sfwiLD//WBVWpGMYLa+PNCGS6hhnAuFkA2psZCmmzkbJbX0N03EdWiWFzV79WPgNI+WzpYIVQ=
